// lib/core/utils/pdf_helper.dart
import 'dart:io';
import 'package:flutter/foundation.dart'; // For debugPrint
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../models/task.dart';

class PdfHelper {
  static Future<void> generateAndSharePdf(List<Task> tasks) async {
    try {
      final pdf = pw.Document();
      final String todayDate = DateFormat('MMMM dd, yyyy').format(DateTime.now());
      final String exactTime = DateFormat('hh:mm a').format(DateTime.now());

      // Filter tasks
      final completedTasks = tasks.where((t) => t.isCompleted).toList();
      final pendingTasks = tasks.where((t) => !t.isCompleted).toList();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          footer: (pw.Context context) {
            return pw.Container(
              alignment: pw.Alignment.centerRight,
              margin: const pw.EdgeInsets.only(top: 20.0),
              child: pw.Text(
                'Generated by LifeOS on $todayDate at $exactTime | Page ${context.pageNumber} of ${context.pagesCount}',
                style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10),
              ),
            );
          },
          build: (pw.Context context) {
            return [
              // --- 🚀 ELITE HEADER ---
              pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text('LifeOS Premium', style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('#6C63FF'))),
                          pw.SizedBox(height: 4),
                          pw.Text('EXECUTIVE MISSION REPORT', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, letterSpacing: 1.2, color: PdfColors.grey700)),
                        ]
                    ),
                    pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.end,
                        children: [
                          pw.Text('Dev: Muhammad Talha', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                          pw.SizedBox(height: 2),
                          pw.Text('Reg: SP23-BCS-086', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                          pw.SizedBox(height: 2),
                          pw.Text('Date: $todayDate', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                        ]
                    ),
                  ]
              ),
              pw.SizedBox(height: 24),
              pw.Divider(color: PdfColors.grey300, thickness: 2),
              pw.SizedBox(height: 24),

              // --- 📊 SUMMARY STATS DASHBOARD ---
              pw.Container(
                  padding: const pw.EdgeInsets.symmetric(vertical: 16, horizontal: 24),
                  decoration: pw.BoxDecoration(
                    color: PdfColor.fromHex('#F8F9FA'),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(12)),
                    border: pw.Border.all(color: PdfColors.grey200, width: 1),
                  ),
                  child: pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
                      children: [
                        _buildStatBox('Total Missions', tasks.length.toString(), PdfColors.indigo),
                        _buildStatBox('Accomplished', completedTasks.length.toString(), PdfColors.green),
                        _buildStatBox('Pending', pendingTasks.length.toString(), PdfColors.orange),
                      ]
                  )
              ),
              pw.SizedBox(height: 32),

              // --- ⏳ PENDING MISSIONS SECTION ---
              _buildSectionHeader('Pending Missions', PdfColors.orange700),
              pw.SizedBox(height: 12),
              if (pendingTasks.isEmpty)
                pw.Text('No pending missions. Your schedule is perfectly clear! 🎉', style: pw.TextStyle(color: PdfColors.grey600, fontStyle: pw.FontStyle.italic))
              else
                ...pendingTasks.map((t) => _buildTaskRow(t)).toList(),

              pw.SizedBox(height: 32),

              // --- ✅ COMPLETED MISSIONS SECTION ---
              _buildSectionHeader('Accomplished Missions', PdfColors.green700),
              pw.SizedBox(height: 12),
              if (completedTasks.isEmpty)
                pw.Text('No missions completed yet. Time to get to work!', style: pw.TextStyle(color: PdfColors.grey600, fontStyle: pw.FontStyle.italic))
              else
                ...completedTasks.map((t) => _buildTaskRow(t)).toList(),
            ];
          },
        ),
      );

      // Save the PDF locally
      final output = await getTemporaryDirectory();
      // File name is cleaned up to avoid space issues
      final file = File('${output.path}/LifeOS_Report_Talha.pdf');
      await file.writeAsBytes(await pdf.save());

      // Trigger the Share/Email dialog
      await Share.shareXFiles(
        [XFile(file.path)],
        text: 'Here is my LifeOS executive task report! 🚀',
        subject: 'LifeOS Task Report - SP23-BCS-086',
      );

    } catch (e) {
      debugPrint("PDF Generation Error: $e");
    }
  }

  // --- 🛠️ Helper widgets for the PDF layout ---

  static pw.Widget _buildSectionHeader(String title, PdfColor color) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 6),
      decoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: color, width: 2))),
      child: pw.Text(title, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: color)),
    );
  }

  static pw.Widget _buildStatBox(String label, String value, PdfColor color) {
    return pw.Column(
        children: [
          pw.Text(value, style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: color)),
          pw.SizedBox(height: 4),
          pw.Text(label, style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700, fontWeight: pw.FontWeight.bold)),
        ]
    );
  }

  static pw.Widget _buildTaskRow(Task task) {
    String formattedDate = DateFormat('MMM dd, yyyy - hh:mm a').format(task.dueDate);

    // Fallback for emojis since custom fonts are needed for actual emojis in PDF
    String moodText = task.moodScore != null ? ' | Mood Score: ${task.moodScore}/5' : '';

    String priorityText = task.priority == 2 ? 'High Priority' : task.priority == 1 ? 'Medium Priority' : 'Low Priority';
    PdfColor priorityColor = task.priority == 2 ? PdfColors.red600 : task.priority == 1 ? PdfColors.orange600 : PdfColors.blue600;

    String categoryText = task.categoryId == 1 ? "Study" : task.categoryId == 2 ? "Health" : task.categoryId == 3 ? "Work" : "Personal";

    return pw.Container(
        margin: const pw.EdgeInsets.only(bottom: 12),
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: task.isCompleted ? PdfColor.fromHex('#F0FFF4') : PdfColors.white,
          border: pw.Border.all(color: PdfColors.grey300),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        ),
        child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Checkbox placeholder
              pw.Container(
                margin: const pw.EdgeInsets.only(right: 12, top: 2),
                width: 14, height: 14,
                decoration: pw.BoxDecoration(
                  shape: pw.BoxShape.circle,
                  color: task.isCompleted ? PdfColors.green : PdfColors.white,
                  border: pw.Border.all(color: task.isCompleted ? PdfColors.green : PdfColors.grey),
                ),
              ),
              pw.Expanded(
                  child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                            task.title,
                            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, decoration: task.isCompleted ? pw.TextDecoration.lineThrough : pw.TextDecoration.none)
                        ),
                        if (task.description != null && task.description!.isNotEmpty) ...[
                          pw.SizedBox(height: 4),
                          pw.Text(task.description!, style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
                        ],
                        pw.SizedBox(height: 8),

                        // Tags Row (Category & Priority)
                        pw.Row(
                            children: [
                              pw.Text('[$categoryText]', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo600)),
                              pw.SizedBox(width: 8),
                              pw.Text('[$priorityText]', style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: priorityColor)),
                              if (task.isCompleted)
                                pw.Text(moodText, style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.purple600)),
                            ]
                        )
                      ]
                  )
              ),
              // Date
              pw.Text(formattedDate, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
            ]
        )
    );
  }
}